"""The species: how each animal of DIRT's grammar looks, for its body plan (rigs.py).

Keyed by the grammar's own words for it (dirt/earth/out/grammar.json, a
biome's life, kind, realm: "wolves", "a lion pride"), each is a body plan, its
proportions, its real colours (coat, pale parts, dark marks, eye) and its
markings, with its source: the English Wikipedia article on the species (its
description; `wiki` is the article's title). Nothing here is the artist's:
the hand and the inks come from the native artist (hands.py).

Left out of the natives on purpose: the six drawn by hand (`CAST`: the red
fox, the American bison, the red squirrel, the bald eagle, the banana slug,
the red deer — each lives only in its artist's home town, characters.json's
`native`); the kinds that are not one animal (wind, blooms, ferns, mould,
leaf fall, fire, grass waves, dunes, dust, schools, sea life) and swarms of
biting flies (mosquitoes, blackflies), termite mounds and bats at dusk. A
species of the grammar not in this table is not yet drawn: the daily pass
adds it (REFINE.md).
"""

CAST = {"red foxes", "American bison", "red squirrels", "bald eagle", "banana slugs", "red deer"}
KINDS = {"herds": 1.0, "hunters": 1.0, "troops": 0.95, "colonies": 0.85, "eagles": 0.85, "waders": 0.85,
         "macaws": 0.8, "soarers": 0.75, "vees": 0.75, "flocks": 0.75, "hummers": 0.75, "frogs": 0.7,
         "snakes": 0.65, "morphos": 0.6, "fireflies": 0.45, "ants": 0.4, "swarms": 0.4}


def col(coat, pale, dark, eye="#2a2420"):
    return {"coat": coat, "pale": pale, "dark": dark, "eye": eye}


# ---- body plans' defaults ---------------------------------------------------------

def mix(*ds):
    out = {}
    for d in ds:
        out.update(d)
    return out


CANID = dict(L=11, legs=8.2, depth=3.0, neck=4.0, neck_up=38, head=2.5, snout=3.3, snout_w=1.15, ears="point", ear=2.4,
             tail="brush", tail_len=8, tail_up=-25, tail_w=1.5, gait="trot", rest="sit", marks=("belly",))
FELID = dict(L=11.5, legs=7.4, depth=3.0, neck=3.0, neck_up=22, head=2.4, snout=1.3, snout_w=1.3, face="short", ears="round",
             ear=1.7, tail="long", tail_len=10, tail_up=-15, tail_w=1.0, gait="walk", rest="lie", marks=("belly",))
URSID = dict(L=12, legs=6.8, depth=4.4, neck=2.4, neck_up=12, head=2.8, snout=2.4, snout_w=1.4, ears="round", ear=1.5,
             tail="short", gait="walk", rest="lie", hump=0.25, leg_w=1.8, marks=())
CERVID = dict(L=11, legs=10, depth=3.1, neck=5, neck_up=55, head=2.1, snout=2.8, snout_w=0.95, ears="long", ear=2.0,
              tail="short", gait="trot", rest="lie", grazer=True, hoof=True, horns="antler", horn=1.0, leg_w=0.95, marks=("belly",))
BOVINE = dict(L=13, legs=7.8, depth=4.3, neck=3, neck_up=18, head=2.6, snout=2.6, snout_w=1.4, ears="side", ear=1.6,
              tail="tuft", tail_len=7, gait="walk", rest="lie", grazer=True, hoof=True, horns="boss", horn=1.0, leg_w=1.5, marks=())
ANTELOPE = dict(L=10, legs=10, depth=2.8, neck=4.6, neck_up=55, head=2.0, snout=2.6, snout_w=0.9, ears="long", ear=1.8,
                tail="short", gait="trot", rest="lie", grazer=True, hoof=True, horns="lyre", horn=1.0, leg_w=0.85, marks=("belly",))
CAPRID = dict(L=10.5, legs=8, depth=3.5, neck=3.6, neck_up=45, head=2.2, snout=2.2, snout_w=1.0, ears="side", ear=1.4,
              tail="short", gait="walk", rest="lie", grazer=True, hoof=True, horns="curve", horn=1.0, leg_w=1.1, marks=("belly",))
SUID = dict(L=11, legs=5.8, depth=4.2, neck=1.5, neck_up=0, head=3.0, snout=3.6, snout_w=1.4, snout_drop=0.5, ears="point",
            ear=1.8, tail="thin", tail_len=3, tail_up=-70, tail_w=0.6, gait="trot", rest="lie", grazer=True, hoof=True, leg_w=1.2, marks=())
EQUID = dict(L=12, legs=10, depth=3.6, neck=6, neck_up=50, head=2.2, snout=3.6, snout_w=1.2, ears="long", ear=1.5,
             tail="long", tail_len=7, tail_up=-65, tail_w=1.3, mane=1.0, hoof=True, grazer=True, gait="trot", rest="lie", marks=())
CAMELID = dict(L=10, legs=11, depth=3.0, neck=7, neck_up=72, head=1.9, snout=2.4, snout_w=1.0, ears="long", ear=1.6,
               tail="short", hoof=True, grazer=True, gait="walk", rest="lie", leg_w=0.9, marks=("belly",))
RODENT = dict(size=0.72, L=9, legs=5, depth=3.6, neck=1.0, neck_up=20, head=2.8, snout=2.0, snout_w=1.3, ears="round", ear=1.2,
              tail="thin", tail_len=5, tail_up=-10, tail_w=0.7, gait="bound", rest="upright", face="short", marks=("belly",))
MONKEY = dict(L=10, legs=7.5, depth=3.0, neck=1.2, neck_up=25, head=2.5, snout=1.0, snout_w=1.1, face="short", ears="small",
              ear=1.2, tail="long", tail_len=12, tail_up=20, tail_w=0.7, primate=True, gait="walk", rest="upright", marks=())
APE = dict(L=9, legs=7, arms=1.35, depth=3.6, neck=1.0, neck_up=20, head=2.8, snout=1.2, snout_w=1.4, face="short", ears="small",
           ear=1.1, tail="none", primate=True, gait="walk", rest="upright", leg_w=1.4, marks=())

PASSERINE = dict(body=3.2, deep=1.9, tilt=25, neck=0.6, neck_up=50, head=1.6, bill="cone", bill_len=1.2, legs=2.2, tail=3.2,
                 tail_drop=20, wing_span=8, gait="fly")
RAPTOR = dict(body=4.2, deep=2.6, tilt=55, neck=0.8, neck_up=70, head=1.9, bill="hook", bill_len=1.6, legs=3.0, leg_w=0.5,
              tail=4, tail_drop=70, wing_span=16, gait="fly", bill_role="pale", leg_role="pale")
VULTURE = dict(body=5, deep=3, tilt=35, neck=1.8, neck_up=55, head=1.4, bare=True, ruff=1.6, bill="hook", bill_len=1.8,
               legs=3, leg_w=0.5, tail=3, tail_drop=40, wing_span=18, gait="fly", bill_role="pale", leg_role="pale")
OWL = dict(body=3.6, deep=3.0, tilt=75, neck=0, head=2.4, disk=True, bill="hook", bill_len=0.6, legs=1.8, tail=2, tail_drop=80,
           wing_span=14, gait="fly")
GOOSE = dict(body=5, deep=2.6, tilt=5, neck=4, neck_up=60, head=1.5, bill="flat", bill_len=2, legs=3, leg_w=0.4, tail=2,
             tail_drop=10, wing_span=14, gait="fly")
WADER = dict(scale=1.0, body=4.6, deep=2.4, tilt=15, neck=6, neck_up=70, head=1.3, bill="long", bill_len=3.2, legs=10, leg_w=0.35, tail=2.4,
             tail_drop=30, wing_span=14, gait="walk")
RATITE = dict(scale=1.0, body=5.5, deep=3.6, tilt=10, neck=6, neck_up=75, head=1.4, bill="flat", bill_len=1.2, legs=9, leg_w=0.8, tail=0,
              ratite=True, gait="walk")
PARROT = dict(body=3.6, deep=2.2, tilt=55, neck=0.4, head=2.0, bill="parrot", bill_len=1.6, legs=2, tail=7, tail_drop=70,
              wing_span=12, gait="fly")
HUMMER = dict(size=1.0, body=2.4, deep=1.2, tilt=40, neck=0.2, head=1.2, bill="long", bill_len=3, legs=0.8, tail=2, wing_span=7, gait="fly")
GROUNDBIRD = dict(body=3.6, deep=2.4, tilt=5, neck=0.5, neck_up=40, head=1.6, bill="cone", bill_len=0.9, legs=2.4, tail=1.4,
                  tail_drop=10, gait="walk")
LIZARD = dict(body=6.0, deep=1.5, head=1.5, snout=1.4, tail=11.0, legs=2.0)
CROC = dict(body=8.0, deep=1.8, head=1.7, snout=2.2, tail=13.0, legs=1.8, croc=True, marks=("scutes", "belly"))
FROG = dict()
SNAKE = dict(thick=1.0, length=30.0, head=1.2)


def S(name, latin, plan, wiki, c, kind=None, size=1.0, **p):
    p.setdefault("size", size)
    return {"name": name, "latin": latin, "plan": plan, "wiki": wiki, "col": c, "p": p}


def Q(base, name, latin, wiki, c, **over):
    return S(name, latin, "quad", wiki, c, **mix(base, over))


def B(base, name, latin, wiki, c, **over):
    return S(name, latin, "bird", wiki, c, **mix(base, over))


SPECIES = {
    # ---- hunters ---------------------------------------------------------------------------
    "wolves": Q(CANID, "Grey wolf", "Canis lupus", "Wolf", col("#8c8378", "#ddd5c6", "#3b342e", "#c9a24a"), size=0.95,
                marks=("belly", "saddle", "muzzle")),
    "grey wolves": Q(CANID, "Grey wolf", "Canis lupus", "Wolf", col("#8a8176", "#ddd6c8", "#3a332d", "#c9a24a"), size=0.95,
                     marks=("belly", "saddle", "muzzle")),
    "Indian wolves": Q(CANID, "Indian wolf", "Canis lupus pallipes", "Indian wolf", col("#a78a68", "#e2d4bb", "#4a3b2c", "#c9a24a"), size=0.85,
                       marks=("belly", "muzzle")),
    "Ethiopian wolves": Q(CANID, "Ethiopian wolf", "Canis simensis", "Ethiopian wolf", col("#b5612b", "#f1e6d2", "#2e2420", "#8a6a3a"), size=0.85,
                          snout=3.8, marks=("belly", "bib", "tailtip_dark")),
    "coyotes": Q(CANID, "Coyote", "Canis latrans", "Coyote", col("#a08a6c", "#e3d8c4", "#3c3128", "#c8a25a"), size=0.85,
                 marks=("belly", "saddle", "tailtip_dark")),
    "golden jackals": Q(CANID, "Golden jackal", "Canis aureus", "Golden jackal", col("#b8915c", "#e8dcc2", "#4a3a2a"), size=0.75,
                        marks=("belly", "saddle")),
    "dholes": Q(CANID, "Dhole", "Cuon alpinus", "Dhole", col("#b2582a", "#e9d8c0", "#2c1f18"), size=0.8, marks=("belly", "tailtip_dark")),
    "African wild dogs": Q(CANID, "African wild dog", "Lycaon pictus", "African wild dog", col("#7a5b38", "#d9c9a2", "#1f1a16"), size=0.85,
                           ears="round", ear=2.2, marks=("spots", "tailtip", "muzzle_dark")),
    "maned wolf": Q(CANID, "Maned wolf", "Chrysocyon brachyurus", "Maned wolf", col("#c4662a", "#efe4d2", "#1e1814"), size=0.95,
                    legs=11, ear=2.8, mane=0.9, marks=("dark_legs", "muzzle_dark", "tailtip", "mane_dark")),
    "arctic foxes": Q(CANID, "Arctic fox", "Vulpes lagopus", "Arctic fox", col("#d9d6cf", "#f5f3ee", "#3a3632"), size=0.7, ear=1.8, snout=2.6,
                      legs=6.8, tail_w=1.9),
    "corsac foxes": Q(CANID, "Corsac fox", "Vulpes corsac", "Corsac fox", col("#b49a7a", "#ece2d0", "#4a3c2e"), size=0.65,
                      marks=("belly", "tailtip_dark")),
    "fennec foxes": Q(CANID, "Fennec fox", "Vulpes zerda", "Fennec fox", col("#dcc092", "#f6eedc", "#5a4632"), size=0.55, ear=3.8, snout=2.4,
                      marks=("belly", "tailtip_dark")),
    "pampas foxes": Q(CANID, "Pampas fox", "Lycalopex gymnocercus", "Pampas fox", col("#8f8578", "#ddd3c2", "#2e2a26"), size=0.75,
                      marks=("belly", "saddle", "tailtip_dark")),
    "culpeo foxes": Q(CANID, "Culpeo", "Lycalopex culpaeus", "Culpeo", col("#a2774c", "#e6d8c0", "#2f2620"), size=0.78,
                      marks=("belly", "tailtip_dark")),
    "Andean foxes": Q(CANID, "Culpeo", "Lycalopex culpaeus", "Culpeo", col("#a2774c", "#e6d8c0", "#2f2620"), size=0.78,
                      marks=("belly", "tailtip_dark")),
    "dingoes": Q(CANID, "Dingo", "Canis familiaris dingo", "Dingo", col("#c48a4a", "#f0e4cc", "#5a3c22"), size=0.85,
                 marks=("belly", "socks", "tailtip")),
    "black-backed jackals": Q(CANID, "Black-backed jackal", "Lupulella mesomelas", "Black-backed jackal",
                              col("#b06a36", "#e9dcc6", "#262220"), size=0.72, marks=("belly", "saddle")),
    "Eurasian lynx": Q(FELID, "Eurasian lynx", "Lynx lynx", "Eurasian lynx", col("#ad8c66", "#ece2d0", "#3a2c22", "#c9a24a"), size=0.85,
                       legs=8.4, ears="tuft", ear=2.0, tail="short", marks=("belly", "spots")),
    "Iberian lynx": Q(FELID, "Iberian lynx", "Lynx pardinus", "Iberian lynx", col("#b8925e", "#efe6d4", "#2c221c", "#c9a24a"), size=0.78,
                      legs=8.2, ears="tuft", ear=2.0, tail="short", marks=("belly", "spots")),
    "Canada lynx": Q(FELID, "Canada lynx", "Lynx canadensis", "Canada lynx", col("#9c9284", "#e2ddd2", "#2e2a26", "#c9a24a"), size=0.82,
                     legs=8.8, ears="tuft", ear=2.0, tail="short", marks=("belly",)),
    "bobcats": Q(FELID, "Bobcat", "Lynx rufus", "Bobcat", col("#a2805e", "#ece2d0", "#2e241c", "#c9a24a"), size=0.75, legs=7.8,
                 ears="tuft", ear=1.7, tail="short", marks=("belly", "spots")),
    "caracals": Q(FELID, "Caracal", "Caracal caracal", "Caracal", col("#b27a48", "#eee2cc", "#221c18", "#c9a24a"), size=0.78, legs=8.4,
                  ears="tuft", ear=2.6, tail_len=6, marks=("belly",)),
    "kodkod": Q(FELID, "Kodkod", "Leopardus guigna", "Kodkod", col("#8c6e48", "#d8c8a8", "#2a221a"), size=0.5, marks=("spots", "ringed")),
    "cougars": Q(FELID, "Cougar", "Puma concolor", "Cougar", col("#b38b5e", "#ece2d2", "#2a221c", "#b89a5a"), size=1.0,
                 marks=("belly", "tailtip_dark", "muzzle")),
    "puma": Q(FELID, "Puma", "Puma concolor", "Cougar", col("#b0885c", "#ece2d2", "#2a221c", "#b89a5a"), size=1.0,
              marks=("belly", "tailtip_dark", "muzzle")),
    "jaguar": Q(FELID, "Jaguar", "Panthera onca", "Jaguar", col("#c4943e", "#f0e4c8", "#1e1a16", "#c9a24a"), size=1.05, legs=6.8, depth=3.4,
                head=2.8, marks=("belly", "rosettes")),
    "leopard": Q(FELID, "Leopard", "Panthera pardus", "Leopard", col("#c9a052", "#f0e6cc", "#1e1a16", "#c9a24a"), size=0.98,
                 marks=("belly", "rosettes")),
    "cheetahs": Q(FELID, "Cheetah", "Acinonyx jubatus", "Cheetah", col("#d2aa62", "#f2e9d2", "#1c1814", "#c9a24a"), size=1.0, legs=9.4,
                  depth=2.6, head=2.1, marks=("belly", "spots", "ringed")),
    "a lion pride": Q(FELID, "Lion", "Panthera leo", "Lion", col("#c79a5c", "#ecdcc0", "#3a2a1e", "#b89a5a"), size=1.12, mane=2.2,
                      tail="long", marks=("belly", "mane_dark", "tailtip_dark")),
    "Bengal tiger": Q(FELID, "Bengal tiger", "Panthera tigris tigris", "Bengal tiger", col("#cf7a2c", "#f2ead8", "#1c1814", "#c9a24a"),
                      size=1.12, depth=3.4, head=2.8, marks=("belly", "stripes")),
    "Amur tiger": Q(FELID, "Siberian tiger", "Panthera tigris tigris", "Siberian tiger", col("#c98a46", "#f3ecdd", "#1e1a16", "#c9a24a"),
                    size=1.15, depth=3.5, head=2.8, marks=("belly", "stripes")),
    "snow leopard": Q(FELID, "Snow leopard", "Panthera uncia", "Snow leopard", col("#c9c2b4", "#efece4", "#3a3632"), size=0.9,
                      tail_len=12, tail_w=1.6, marks=("belly", "rosettes")),
    "a spotted hyena clan": Q(CANID, "Spotted hyena", "Crocuta crocuta", "Spotted hyena", col("#a88c66", "#d8c8a8", "#2a221a"), size=0.95,
                              ears="round", ear=1.8, tail="tuft", tail_len=5, depth=3.4, sag=-0.6, marks=("spots", "muzzle_dark")),
    "black bears": Q(URSID, "American black bear", "Ursus americanus", "American black bear", col("#2c2724", "#7a6650", "#1a1716", "#5a4030"),
                     size=0.95, marks=("muzzle",)),
    "Asiatic black bears": Q(URSID, "Asian black bear", "Ursus thibetanus", "Asian black bear", col("#2a2624", "#e6dcc6", "#141210"),
                             size=0.95, marks=("bib",)),
    "brown bears": Q(URSID, "Brown bear", "Ursus arctos", "Brown bear", col("#6e4c30", "#a07c58", "#2a1e16", "#3a2a1e"), size=1.08, hump=0.6),
    "grizzly bears": Q(URSID, "Grizzly bear", "Ursus arctos horribilis", "Grizzly bear", col("#80603e", "#c4a47a", "#2c2018", "#3a2a1e"),
                       size=1.08, hump=0.7),
    "a polar bear": Q(URSID, "Polar bear", "Ursus maritimus", "Polar bear", col("#e3dccb", "#f6f2e8", "#262220"), size=1.1, neck=3.8),
    "sable": Q(CANID, "Sable", "Martes zibellina", "Sable", col("#4a3424", "#c8a46c", "#1e1610"), size=0.55, L=12, legs=4.6, ears="round",
               ear=1.4, snout=2.0, tail="brush", tail_len=6, gait="bound", rest="sit", marks=("bib",)),

    # ---- herds ------------------------------------------------------------------------------
    "wild boar": Q(SUID, "Wild boar", "Sus scrofa", "Wild boar", col("#4e3e30", "#8a7660", "#1e1814", "#2a2018"), size=0.9, mane=0.7,
                   tusks=0.5, marks=("dorsal",)),
    "collared peccaries": Q(SUID, "Collared peccary", "Dicotyles tajacu", "Collared peccary", col("#4a4440", "#b8b0a2", "#1e1a18"), size=0.7,
                            tail="none", marks=("bib",)),
    "bushpigs": Q(SUID, "Bushpig", "Potamochoerus larvatus", "Bushpig", col("#8a4a28", "#d8cfc0", "#2a1e18"), size=0.82, marks=("dorsal",)),
    "white-tailed deer": Q(CERVID, "White-tailed deer", "Odocoileus virginianus", "White-tailed deer",
                           col("#a87a52", "#efe8dc", "#2e2620"), size=0.9, horns="forward", marks=("belly", "rump", "muzzle")),
    "mule deer": Q(CERVID, "Mule deer", "Odocoileus hemionus", "Mule deer", col("#8a7e70", "#ece6da", "#2e2a26"), size=0.9, ear=2.8,
                   horns="forward", marks=("belly", "rump", "pale_face")),
    "Roosevelt elk": Q(CERVID, "Roosevelt elk", "Cervus canadensis roosevelti", "Roosevelt elk", col("#9a7650", "#d8c6a4", "#3e2c1e"),
                       size=1.08, mane=1.0, marks=("rump", "mane_dark")),
    "moose": Q(CERVID, "Moose", "Alces alces", "Moose", col("#3e2e24", "#8a7a68", "#1c1612"), size=1.12, legs=11, horns="palm", horn=1.2,
               snout=3.4, snout_w=1.4, hump=0.6, beard=0.8, marks=("pale_legs",)),
    "elk (moose)": Q(CERVID, "Moose", "Alces alces", "Moose", col("#3e2e24", "#8a7a68", "#1c1612"), size=1.12, legs=11, horns="palm", horn=1.2,
                     snout=3.4, snout_w=1.4, hump=0.6, beard=0.8, marks=("pale_legs",)),
    "reindeer": Q(CERVID, "Reindeer", "Rangifer tarandus", "Reindeer", col("#8a7e6e", "#ebe6da", "#3a342e"), size=0.95, horns="caribou",
                  horn=1.1, mane=0.8, marks=("belly", "rump")),
    "caribou": Q(CERVID, "Caribou", "Rangifer tarandus", "Reindeer", col("#7e6c5a", "#ebe6da", "#3a342e"), size=0.95, horns="caribou",
                 horn=1.1, mane=0.8, marks=("belly", "rump")),
    "woodland caribou": Q(CERVID, "Woodland caribou", "Rangifer tarandus caribou", "Boreal woodland caribou",
                          col("#6e5a48", "#e6e0d2", "#2e2620"), size=0.95, horns="caribou", horn=1.1, mane=0.8, marks=("rump",)),
    "chital": Q(CERVID, "Chital", "Axis axis", "Chital", col("#b8743a", "#f2ebdc", "#3a2a1c"), size=0.85, marks=("belly", "spots", "dorsal")),
    "sambar": Q(CERVID, "Sambar", "Rusa unicolor", "Sambar deer", col("#5e4a38", "#b0a088", "#241c16"), size=1.05, horn=0.8, mane=0.6),
    "sika deer": Q(CERVID, "Sika deer", "Cervus nippon", "Sika deer", col("#9a6a3e", "#efe6d4", "#3a2a1e"), size=0.82, marks=("spots", "rump")),
    "pampas deer": Q(CERVID, "Pampas deer", "Ozotoceros bezoarticus", "Pampas deer", col("#b28e5e", "#efe6d6", "#3e3024"), size=0.78,
                     horn=0.8, marks=("belly", "rump")),
    "marsh deer": Q(CERVID, "Marsh deer", "Blastocerus dichotomus", "Marsh deer", col("#a65c30", "#e6d8c0", "#1e1814"), size=0.98,
                    marks=("dark_legs", "muzzle_dark")),
    "pudu": Q(CERVID, "Southern pudú", "Pudu puda", "Pudú", col("#7a5638", "#b8946c", "#2a1e16"), size=0.5, legs=6.5, horns="prong",
              horn=0.5, marks=()),
    "musk deer": Q(CERVID, "Musk deer", "Moschus", "Musk deer", col("#6a5440", "#b8a688", "#2a2018"), size=0.6, horns=None, tusks=0.4),
    "hog deer": Q(CERVID, "Hog deer", "Axis porcinus", "Hog deer", col("#8a6440", "#d8c8ac", "#2a2018"), size=0.65, legs=7.5),
    "swamp deer": Q(CERVID, "Barasingha", "Rucervus duvaucelii", "Barasingha", col("#a87a44", "#e6dcc6", "#3a2a1c"), size=1.0, horn=1.2),
    "pronghorn": Q(ANTELOPE, "Pronghorn", "Antilocapra americana", "Pronghorn", col("#c08a4e", "#f4efe4", "#1e1a16"), size=0.9,
                   horns="prong", horn=1.0, marks=("belly", "rump", "bib")),
    "Thomson's gazelle": Q(ANTELOPE, "Thomson's gazelle", "Eudorcas thomsonii", "Thomson's gazelle", col("#c08a52", "#f4efe6", "#1e1a16"),
                           size=0.72, marks=("belly", "flank", "rump")),
    "dorcas gazelles": Q(ANTELOPE, "Dorcas gazelle", "Gazella dorcas", "Dorcas gazelle", col("#d2a874", "#f6efe2", "#5a4430"), size=0.68,
                         marks=("belly", "flank")),
    "Mongolian gazelles": Q(ANTELOPE, "Mongolian gazelle", "Procapra gutturosa", "Mongolian gazelle", col("#c9a678", "#f2ebdc", "#4a3a2a"),
                            size=0.78, horn=0.7, marks=("belly", "rump")),
    "chinkara": Q(ANTELOPE, "Chinkara", "Gazella bennettii", "Chinkara", col("#b88a5a", "#efe6d6", "#3a2c20"), size=0.68, marks=("belly", "flank")),
    "blackbuck": Q(ANTELOPE, "Blackbuck", "Antilope cervicapra", "Blackbuck", col("#2a2420", "#f2ede4", "#141210"), size=0.78, horns="straight",
                   horn=0.9, marks=("belly", "pale_face")),
    "springbok": Q(ANTELOPE, "Springbok", "Antidorcas marsupialis", "Springbok", col("#c48a4a", "#f6f2ea", "#3a2a1c"), size=0.75,
                   marks=("belly", "flank")),
    "impala": Q(ANTELOPE, "Impala", "Aepyceros melampus", "Impala", col("#b06a38", "#f2e9da", "#1e1814"), size=0.82, horn=1.2,
                marks=("belly", "flank")),
    "saiga": Q(ANTELOPE, "Saiga antelope", "Saiga tatarica", "Saiga antelope", col("#c4a47a", "#f0e8d8", "#4a3a2a"), size=0.72, legs=8.2,
               snout=2.4, snout_w=1.4, horn=0.6, marks=("belly",)),
    "Tibetan antelope": Q(ANTELOPE, "Tibetan antelope", "Pantholops hodgsonii", "Tibetan antelope", col("#b8a084", "#f0ebe2", "#2a2420"),
                          size=0.8, horns="straight", marks=("belly", "muzzle_dark")),
    "addax": Q(ANTELOPE, "Addax", "Addax nasomaculatus", "Addax", col("#e2d6c2", "#f6f2ea", "#6a5440"), size=0.95, horns="spiral", horn=1.1,
               marks=("muzzle_dark",)),
    "gemsbok": Q(ANTELOPE, "Gemsbok", "Oryx gazella", "Gemsbok", col("#b8a88e", "#f0ece4", "#1c1a18"), size=1.0, horns="straight", horn=1.2,
                 marks=("flank", "mask", "belly")),
    "bontebok": Q(ANTELOPE, "Bontebok", "Damaliscus pygargus pygargus", "Bontebok", col("#6a3a26", "#f4f0ea", "#2a1a14"), size=0.85,
                  horns="short", marks=("pale_face", "belly", "rump")),
    "blue wildebeest": Q(BOVINE, "Blue wildebeest", "Connochaetes taurinus", "Blue wildebeest", col("#5c5a58", "#a8a49c", "#1e1c1a"),
                         size=0.95, legs=9, horns="short", mane=1.0, beard=0.8, marks=("stripes", "mane_dark")),
    "black wildebeest": Q(BOVINE, "Black wildebeest", "Connochaetes gnou", "Black wildebeest", col("#3a302a", "#e6e0d4", "#141210"),
                          size=0.9, legs=9, horns="short", beard=0.8),
    "Cape buffalo": Q(BOVINE, "African buffalo", "Syncerus caffer", "African buffalo", col("#2c2826", "#5a524c", "#141210"), size=1.1, horn=1.3),
    "gaur": Q(BOVINE, "Gaur", "Bos gaurus", "Gaur", col("#3a2820", "#e8e0cc", "#1a1412"), size=1.12, legs=8.6, hump=0.6, horns="short",
              marks=("socks",)),
    "muskoxen": Q(BOVINE, "Muskox", "Ovibos moschatus", "Muskox", col("#3e3026", "#c8b89c", "#1c1612"), size=0.95, legs=6.2, hump=0.6,
                  horns="boss", marks=("saddle",)),
    "wild yak": Q(BOVINE, "Wild yak", "Bos mutus", "Wild yak", col("#2a2420", "#6a5a4a", "#141210"), size=1.1, hump=0.6, horns="short"),
    "water buffalo": Q(BOVINE, "Water buffalo", "Bubalus bubalis", "Water buffalo", col("#3a3634", "#7a726a", "#1a1816"), size=1.05, horn=1.3),
    "Iberian ibex": Q(CAPRID, "Iberian ibex", "Capra pyrenaica", "Iberian ibex", col("#9a7650", "#e6dccb", "#2a221c"), size=0.85,
                      horn=1.1, beard=0.5, marks=("belly", "dark_legs")),
    "walia ibex": Q(CAPRID, "Walia ibex", "Capra walie", "Walia ibex", col("#6e5038", "#d8cab0", "#2a1e16"), size=0.88, horn=1.3, beard=0.6,
                    marks=("belly",)),
    "mouflon": Q(CAPRID, "Mouflon", "Ovis gmelini", "Mouflon", col("#7a4a2c", "#f0e8da", "#2a1e18"), size=0.8, horns="spiral", horn=1.0,
                 marks=("belly", "saddle", "muzzle", "socks")),
    "desert bighorn sheep": Q(CAPRID, "Desert bighorn sheep", "Ovis canadensis nelsoni", "Desert bighorn sheep",
                              col("#a68866", "#efe8da", "#3a2e24"), size=0.88, horns="spiral", horn=1.2, marks=("rump", "belly", "muzzle")),
    "mountain goats": Q(CAPRID, "Mountain goat", "Oreamnos americanus", "Mountain goat", col("#ebe6da", "#f8f6f0", "#262220"), size=0.85,
                        horns="short", horn=0.7, beard=0.8),
    "blue sheep": Q(CAPRID, "Bharal", "Pseudois nayaur", "Bharal", col("#8a8478", "#ece8e0", "#2a2622"), size=0.82, horns="spiral",
                    marks=("belly", "flank")),
    "goral": Q(CAPRID, "Himalayan goral", "Naemorhedus goral", "Himalayan goral", col("#8a7a66", "#e6dece", "#3a3028"), size=0.7, horns="short",
               horn=0.6, marks=("bib",)),
    "Himalayan tahr": Q(CAPRID, "Himalayan tahr", "Hemitragus jemlahicus", "Himalayan tahr", col("#7a5638", "#c8a880", "#2a1e16"), size=0.9,
                        horns="short", mane=1.0),
    "geladas": Q(MONKEY, "Gelada", "Theropithecus gelada", "Gelada", col("#8a6440", "#d8c4a0", "#2a1e16"), size=0.85, snout=2.0, mane=1.4,
                 tail="long", tail_len=8, tail_up=-30, marks=("bib",)),
    "Przewalski's horses": Q(EQUID, "Przewalski's horse", "Equus ferus przewalskii", "Przewalski's horse", col("#b48650", "#ecdcc0", "#2a2018"),
                             size=0.95, mane=0.8, marks=("dark_legs", "muzzle", "mane_dark", "dorsal")),
    "plains zebra": Q(EQUID, "Plains zebra", "Equus quagga", "Plains zebra", col("#ece8de", "#f6f4ee", "#1a1816"), size=0.98, mane=0.9,
                      marks=("stripes", "mane_dark", "muzzle_dark")),
    "kiang": Q(EQUID, "Kiang", "Equus kiang", "Kiang", col("#a8683a", "#f0e8da", "#2e221a"), size=0.95, marks=("belly", "dorsal", "pale_legs")),
    "Indian wild ass": Q(EQUID, "Indian wild ass", "Equus hemionus khur", "Indian wild ass", col("#b49a7a", "#f0e8da", "#3a2e24"), size=0.9,
                         ear=2.0, marks=("belly", "dorsal")),
    "guanacos": Q(CAMELID, "Guanaco", "Lama guanicoe", "Guanaco", col("#b0784a", "#f0e8da", "#3a3230"), size=0.95, marks=("belly",)),
    "vicuñas": Q(CAMELID, "Vicuña", "Lama vicugna", "Vicuña", col("#c08c5a", "#f4eee4", "#4a3a2c"), size=0.85, marks=("belly", "bib")),
    "dromedaries": Q(CAMELID, "Dromedary", "Camelus dromedarius", "Dromedary", col("#c4a07a", "#e0cbb0", "#5a4634"), size=1.1, legs=11.5,
                     neck=6.5, neck_up=35, hump=1.2, tail="tuft", marks=()),
    "African elephants": Q(dict(L=11.5, legs=9, depth=5.0, neck=3.4, neck_up=8, neck_w=2.6, head=3.2, snout=1.2, snout_w=2.0, snout_drop=0.6, ears="big", ear=3.0,
                                trunk=7.5, tusks=1, tail="tuft", tail_len=6, leg_w=2.3, gait="walk", rest="lie", grazer=False, hoof=False,
                                marks=()),
                           "African bush elephant", "Loxodonta africana", "African bush elephant", col("#8a8480", "#bdb6ae", "#3e3a36"), size=0.95),
    "giraffes": Q(dict(L=8.6, legs=15, depth=3.4, neck=13, neck_up=68, neck_w=1.5, head=1.9, snout=2.4, snout_w=0.9, ears="long", ear=1.4,
                       horns="ossicone", horn=1.0, horn_dark=True, tail="tuft", tail_len=9, hoof=True, grazer=True, gait="walk", rest="lie",
                       mane=0.6, canvas=(36, 42), marks=("patches", "mane_dark")),
                  "Giraffe", "Giraffa camelopardalis", "Giraffe", col("#c88a46", "#f2e6cc", "#5a3418"), size=1.0),
    "capybara": Q(dict(L=10, legs=5.4, depth=4.0, neck=1.4, neck_up=10, head=3.0, snout=2.4, snout_w=1.8, ears="small", ear=1.3,
                       tail="none", gait="walk", rest="lie", grazer=True, face="long", marks=()),
                  "Capybara", "Hydrochoerus hydrochaeris", "Capybara", col("#8a6a48", "#b89a78", "#3a2a1e"), size=0.75),
    "greater rheas": B(RATITE, "Greater rhea", "Rhea americana", "Greater rhea", col("#8a8274", "#d8d2c4", "#2e2a26"), size=1.0,
                       dark_parts=("neck",), bill_role="pale"),
    "emus": B(RATITE, "Emu", "Dromaius novaehollandiae", "Emu", col("#5a4a3a", "#9a8a78", "#1e1a16"), size=1.05, bill_role="dark"),
    "eastern grey kangaroos": S("Eastern grey kangaroo", "Macropus giganteus", "hopper", "Eastern grey kangaroo",
                                col("#8a8076", "#ddd6ca", "#2e2a26"), marks=("belly",)),
    "western grey kangaroos": S("Western grey kangaroo", "Macropus fuliginosus", "hopper", "Western grey kangaroo",
                                col("#7a6a5c", "#cfc4b4", "#2a2420"), marks=("belly",)),
    "red kangaroos": S("Red kangaroo", "Osphranter rufus", "hopper", "Red kangaroo", col("#b05a32", "#efe4d6", "#2e221a"), size=1.08,
                       marks=("belly",)),
    "agile wallabies": S("Agile wallaby", "Notamacropus agilis", "hopper", "Agile wallaby", col("#b0946e", "#ece4d6", "#3a2e24"),
                         size=0.75, marks=("belly",)),

    # ---- troops ------------------------------------------------------------------------------
    "grey squirrels": Q(RODENT, "Eastern grey squirrel", "Sciurus carolinensis", "Eastern gray squirrel", col("#8a8680", "#ece8e2", "#3a3632"),
                        size=0.62, tail="squirrel", tail_w=1.6, ears="round", rest="upright", marks=("belly",)),
    "Douglas squirrels": Q(RODENT, "Douglas squirrel", "Tamiasciurus douglasii", "Douglas squirrel", col("#6a5440", "#e0a85a", "#2a1e16"),
                           size=0.55, tail="squirrel", tail_w=1.3, marks=("belly",)),
    "Mexican grey squirrels": Q(RODENT, "Mexican grey squirrel", "Sciurus aureogaster", "Mexican gray squirrel",
                                col("#7a7670", "#c8643a", "#2e2a26"), size=0.6, tail="squirrel", tail_w=1.6, marks=("belly",)),
    "Himalayan striped squirrels": Q(RODENT, "Himalayan striped squirrel", "Tamiops mcclellandii", "Himalayan striped squirrel",
                                     col("#6a5a46", "#e6d6b8", "#1e1814"), size=0.45, tail="squirrel", marks=("belly", "dorsal")),
    "brushtail possums": Q(dict(L=9, legs=5, depth=3.2, neck=1.0, neck_up=20, head=2.4, snout=1.8, snout_w=1.1, ears="point", ear=1.8,
                                tail="brush", tail_len=9, tail_up=-30, tail_w=1.2, gait="walk", rest="upright", marks=("belly", "tailtip_dark")),
                           "Common brushtail possum", "Trichosurus vulpecula", "Common brushtail possum", col("#7a7672", "#ece6dc", "#1e1c1a"),
                           size=0.6),
    "monito del monte": Q(RODENT, "Monito del monte", "Dromiciops gliroides", "Monito del monte", col("#8a6a4a", "#e0d0b8", "#2a1e16"),
                          size=0.45, tail="thin", tail_len=7, marks=("belly", "mask")),
    "spider monkeys": Q(MONKEY, "Black-handed spider monkey", "Ateles geoffroyi", "Geoffroy's spider monkey", col("#7a5032", "#d8b48a", "#1e1612"),
                        size=0.85, legs=9, arms=1.2, tail_len=15, marks=("dark_legs",)),
    "howler monkeys": Q(MONKEY, "Howler monkey", "Alouatta", "Howler monkey", col("#2e2420", "#8a5a30", "#141010"), size=0.85, beard=0.8),
    "golden lion tamarins": Q(MONKEY, "Golden lion tamarin", "Leontopithecus rosalia", "Golden lion tamarin", col("#e0882a", "#f4c870", "#3a1e10"),
                              size=0.5, mane=1.2, tail_up=-20),
    "white-faced capuchins": Q(MONKEY, "White-faced capuchin", "Cebus imitator", "Panamanian white-faced capuchin",
                               col("#221c1a", "#ece2cc", "#100c0a"), size=0.68, marks=("pale_face", "bib")),
    "colobus monkeys": Q(MONKEY, "Mantled guereza", "Colobus guereza", "Mantled guereza", col("#1e1c1a", "#f2efe8", "#0e0c0a"), size=0.8,
                         tail_len=14, marks=("tailtip", "pale_face")),
    "chimpanzees": Q(APE, "Chimpanzee", "Pan troglodytes", "Chimpanzee", col("#2a2420", "#8a7462", "#141210"), size=0.95, marks=("pale_face",)),
    "gibbons": Q(APE, "Lar gibbon", "Hylobates lar", "Lar gibbon", col("#3a2e26", "#e6dccb", "#1a1612"), size=0.72, arms=1.6, marks=("pale_face",)),
    "orangutans": Q(APE, "Bornean orangutan", "Pongo pygmaeus", "Bornean orangutan", col("#a8481e", "#c87a4a", "#3a1a0e"), size=1.0, arms=1.6),
    "lemurs": Q(MONKEY, "Ring-tailed lemur", "Lemur catta", "Ring-tailed lemur", col("#8a8480", "#ece8e2", "#1e1c1a"), size=0.7, snout=2.0,
                face="long", ears="point", ear=1.4, tail_len=13, marks=("ringed", "belly", "mask")),
    "Verreaux's sifakas": Q(MONKEY, "Verreaux's sifaka", "Propithecus verreauxi", "Verreaux's sifaka", col("#ece8e0", "#f8f6f2", "#2a2420"),
                            size=0.75, marks=("muzzle_dark",)),
    "grey langurs": Q(MONKEY, "Grey langur", "Semnopithecus", "Gray langur", col("#a8a29a", "#e6e2da", "#1e1c1a"), size=0.82, tail_len=15,
                      tail_up=40, marks=("pale_face",)),
    "rhesus macaques": Q(MONKEY, "Rhesus macaque", "Macaca mulatta", "Rhesus macaque", col("#9a8264", "#d8c8ae", "#5a3a2a"), size=0.72,
                         snout=1.6, tail_len=5, tail_up=-30),
    "long-tailed macaques": Q(MONKEY, "Crab-eating macaque", "Macaca fascicularis", "Crab-eating macaque", col("#8a7a62", "#cfc4b0", "#3a2e24"),
                              size=0.68, snout=1.6, tail_len=12),
    "proboscis monkeys": Q(MONKEY, "Proboscis monkey", "Nasalis larvatus", "Proboscis monkey", col("#b8784a", "#e6d6c0", "#4a2a1a"), size=0.85,
                           snout=2.2, snout_drop=0.6, marks=("pale_legs",)),
    "tree kangaroos": S("Tree kangaroo", "Dendrolagus", "hopper", "Tree-kangaroo", col("#8a4a2a", "#d8b48a", "#2a1a12"), size=0.75),

    # ---- colonies -------------------------------------------------------------------------------
    "a prairie-dog town": Q(RODENT, "Black-tailed prairie dog", "Cynomys ludovicianus", "Black-tailed prairie dog",
                            col("#b8946a", "#e6d8c2", "#2a2018"), size=0.55, tail="short", ears="small", marks=("belly",)),
    "bobak marmots": Q(RODENT, "Bobak marmot", "Marmota bobak", "Bobak marmot", col("#b49a72", "#e0d0b4", "#4a3a2a"), size=0.68, tail="short",
                       ears="small", marks=("belly",)),
    "marmots": Q(RODENT, "Marmot", "Marmota", "Marmot", col("#8a6a4a", "#c8aa86", "#2a2018"), size=0.65, tail="thin", tail_len=4, ears="small"),
    "sousliks": Q(RODENT, "European ground squirrel", "Spermophilus citellus", "European ground squirrel", col("#a89270", "#e6dac6", "#3a3024"),
                  size=0.48, tail="thin", tail_len=3.6, ears="small", marks=("belly",)),
    "great gerbils": Q(RODENT, "Great gerbil", "Rhombomys opimus", "Great gerbil", col("#c4a274", "#f0e6d4", "#3a2e22"), size=0.45, tail_len=8,
                       marks=("belly", "tailtip_dark")),
    "kangaroo rats": Q(RODENT, "Kangaroo rat", "Dipodomys", "Kangaroo rat", col("#c4a07a", "#f4eee4", "#3a2e24"), size=0.42, legs=6, tail_len=12,
                       gait="bound", marks=("belly", "tailtip")),
    "viscachas": Q(RODENT, "Plains viscacha", "Lagostomus maximus", "Plains viscacha", col("#8a8478", "#e8e2d6", "#1e1c1a"), size=0.62,
                   tail_len=5, marks=("belly", "mask")),
    "meerkats": Q(RODENT, "Meerkat", "Suricata suricatta", "Meerkat", col("#b49a7a", "#e6dac4", "#2a2018"), size=0.5, tail_len=6,
                  marks=("belly", "mask", "tailtip_dark")),
    "lemmings": Q(RODENT, "Brown lemming", "Lemmus trimucronatus", "Nearctic brown lemming", col("#8a6a4a", "#c8a880", "#2a1e16"), size=0.36,
                  tail="short", ears="small", marks=("dorsal",)),
    "giant mole-rats": Q(RODENT, "Giant root-rat", "Tachyoryctes macrocephalus", "Giant root-rat", col("#8a6c4c", "#b8a084", "#2a1e16"),
                         size=0.52, tail="short", ears="none"),
    "pikas": Q(RODENT, "Pika", "Ochotona", "Pika", col("#9a8a74", "#d8ccb8", "#3a3026"), size=0.4, tail="none", ears="round", ear=1.6),
    "burrowing owls": B(OWL, "Burrowing owl", "Athene cunicularia", "Burrowing owl", col("#9a7a54", "#efe6d4", "#3a2c20", "#e0c040"), size=0.8,
                        legs=4.2, gait="walk", pale_parts=("belly", "throat"), marks=("spots",)),

    # ---- birds of prey -------------------------------------------------------------------------------
    "white-tailed eagle": B(RAPTOR, "White-tailed eagle", "Haliaeetus albicilla", "White-tailed eagle", col("#6a5440", "#efebe2", "#2a2018", "#e0c040"),
                            size=1.05, pale_parts=("tail",), bill_role="eye"),
    "golden eagle": B(RAPTOR, "Golden eagle", "Aquila chrysaetos", "Golden eagle", col("#5a4030", "#c4904a", "#241a14", "#c08a30"), size=1.05,
                      pale_parts=("neck",), bill_role="dark"),
    "Bonelli's eagle": B(RAPTOR, "Bonelli's eagle", "Aquila fasciata", "Bonelli's eagle", col("#4a3a30", "#efe8dc", "#1e1814", "#e0a040"),
                         pale_parts=("belly", "breast"), marks=("spots",)),
    "Verreaux's eagle": B(RAPTOR, "Verreaux's eagle", "Aquila verreauxii", "Verreaux's eagle", col("#1e1c1a", "#ece8e0", "#0e0c0a", "#c08a30"),
                          size=1.05, pale_parts=("wing_patch",)),
    "crowned eagle": B(RAPTOR, "Crowned eagle", "Stephanoaetus coronatus", "Crowned eagle", col("#3a2e26", "#d8c4a4", "#1a1612", "#e0c040"),
                       crest=1.6, pale_parts=("belly",), marks=("bars",)),
    "harpy eagle": B(RAPTOR, "Harpy eagle", "Harpia harpyja", "Harpy eagle", col("#3a3836", "#efebe4", "#141210", "#a08050"), size=1.08,
                     crest=1.8, pale_parts=("belly", "head"), dark_parts=("breast_dark",)),
    "Philippine eagle": B(RAPTOR, "Philippine eagle", "Pithecophaga jefferyi", "Philippine eagle", col("#5a4434", "#ece4d8", "#1e1814", "#a8b0c0"),
                          size=1.08, crest=2.0, bill="heavy", bill_len=2.0, pale_parts=("belly", "head")),
    "black-chested buzzard-eagle": B(RAPTOR, "Black-chested buzzard-eagle", "Geranoaetus melanoleucus", "Black-chested buzzard-eagle",
                                     col("#4a4e54", "#e6e4de", "#1e2024", "#a07040"), dark_parts=("breast_dark",), pale_parts=("belly",)),
    "steppe eagles": B(RAPTOR, "Steppe eagle", "Aquila nipalensis", "Steppe eagle", col("#6a5440", "#b89870", "#2a2018", "#a07040"), size=1.0),
    "mountain hawk-eagle": B(RAPTOR, "Mountain hawk-eagle", "Nisaetus nipalensis", "Mountain hawk-eagle", col("#5a4434", "#e6dccb", "#1e1814"),
                             crest=1.4, pale_parts=("belly",), marks=("bars",)),
    "swamp harrier": B(RAPTOR, "Swamp harrier", "Circus approximans", "Swamp harrier", col("#6a5240", "#d8c4a4", "#2a2018", "#e0c040"),
                       size=0.9, legs=4, tail=5, pale_parts=("belly",)),
    "marsh harrier": B(RAPTOR, "Western marsh harrier", "Circus aeruginosus", "Western marsh harrier", col("#6a4a30", "#d8c8a8", "#2a1e16", "#e0c040"),
                       size=0.9, legs=4, tail=5, pale_parts=("head",)),
    "snail kite": B(RAPTOR, "Snail kite", "Rostrhamus sociabilis", "Snail kite", col("#3e4248", "#e6e2dc", "#1e2024", "#e04a2a"), size=0.85,
                    bill_len=2.0, bill_role="dark", leg_role="eye", pale_parts=("tail",)),
    "Fiji goshawk": B(RAPTOR, "Fiji goshawk", "Accipiter rufitorques", "Fiji goshawk", col("#5a6068", "#d8a48a", "#2a2e34", "#e0a040"), size=0.75,
                      pale_parts=("belly", "breast")),
    "gyrfalcon": B(RAPTOR, "Gyrfalcon", "Falco rusticolus", "Gyrfalcon", col("#d8d4cc", "#f4f2ee", "#3a3632", "#2a2420"), size=0.9, crest=0,
                   marks=("spots",)),
    "snowy owl": B(OWL, "Snowy owl", "Bubo scandiacus", "Snowy owl", col("#ece8e0", "#f8f6f2", "#3a3632", "#e0c040"), size=1.0, marks=("bars",),
                   disk=False),
    "rough-legged buzzard": B(RAPTOR, "Rough-legged buzzard", "Buteo lagopus", "Rough-legged buzzard", col("#6a5440", "#e6dccb", "#2a2018"),
                              pale_parts=("head",), dark_parts=("breast_dark",)),
    "red-tailed hawks": B(RAPTOR, "Red-tailed hawk", "Buteo jamaicensis", "Red-tailed hawk", col("#6a4a32", "#efe6d6", "#2a1e16", "#a07040"),
                          size=0.92, pale_parts=("belly", "breast"), dark_parts=("tail",), marks=("bars",)),
    "Harris's hawks": B(RAPTOR, "Harris's hawk", "Parabuteo unicinctus", "Harris's hawk", col("#3a2a22", "#a85a30", "#1a1410", "#a07040"),
                        size=0.9, pale_parts=("tail",), dark_parts=("wing_patch",), bill_role="eye"),
    "chimango caracaras": B(RAPTOR, "Chimango caracara", "Milvago chimango", "Chimango caracara", col("#8a6c50", "#d8c8b0", "#3a2c20"), size=0.75),
    "turkey vultures": B(VULTURE, "Turkey vulture", "Cathartes aura", "Turkey vulture", col("#3a302c", "#c84a3a", "#1c1816"), size=0.98,
                         bare=True, ruff=0.0, marks=("bare_pale",), pale_parts=("head",), dark_parts=("primaries",)),
    "black vultures": B(VULTURE, "Black vulture", "Coragyps atratus", "Black vulture", col("#2a2624", "#8a8682", "#141210"), size=0.92,
                        ruff=0.0, dark_parts=("head",)),
    "king vultures": B(VULTURE, "King vulture", "Sarcoramphus papa", "King vulture", col("#ece6d8", "#e88a3a", "#1e1a18"), size=1.0,
                       ruff=1.4, pale_parts=("head",), dark_parts=("primaries", "ruff", "tail")),
    "California condors": B(VULTURE, "California condor", "Gymnogyps californianus", "California condor", col("#262220", "#e4a07c", "#121010"),
                            size=1.12, ruff=1.6, pale_parts=("head", "wing_patch"), dark_parts=("ruff",)),
    "Andean condors": B(VULTURE, "Andean condor", "Vultur gryphus", "Andean condor", col("#262220", "#efebe4", "#121010"), size=1.15,
                        ruff=1.6, pale_parts=("ruff", "wing_patch")),
    "griffon vultures": B(VULTURE, "Griffon vulture", "Gyps fulvus", "Griffon vulture", col("#a88a64", "#efe8dc", "#2e241c"), size=1.1,
                          pale_parts=("ruff", "head"), dark_parts=("primaries", "tail")),
    "cinereous vultures": B(VULTURE, "Cinereous vulture", "Aegypius monachus", "Cinereous vulture", col("#3a302a", "#8a7a6a", "#1a1612"),
                            size=1.12, dark_parts=("ruff",)),
    "lappet-faced vultures": B(VULTURE, "Lappet-faced vulture", "Torgos tracheliotos", "Lappet-faced vulture", col("#3e322a", "#d89a8a", "#1a1612"),
                               size=1.12, pale_parts=("head", "belly")),
    "white-backed vultures": B(VULTURE, "White-backed vulture", "Gyps africanus", "White-backed vulture", col("#6a5a4a", "#e6dccb", "#2a2018"),
                               size=1.05, pale_parts=("ruff",), dark_parts=("primaries",)),
    "Rüppell's vultures": B(VULTURE, "Rüppell's vulture", "Gyps rueppelli", "Rüppell's vulture", col("#5a4434", "#e6dccb", "#241a14"), size=1.05,
                            pale_parts=("ruff",), marks=("spots",)),
    "white-rumped vultures": B(VULTURE, "White-rumped vulture", "Gyps bengalensis", "White-rumped vulture", col("#2a2624", "#ece8e0", "#141210"),
                               size=1.0, pale_parts=("ruff", "tail")),
    "Egyptian vultures": B(VULTURE, "Egyptian vulture", "Neophron percnopterus", "Egyptian vulture", col("#ece6da", "#f0c040", "#1e1a18"),
                           size=0.85, ruff=0.8, dark_parts=("primaries",), pale_parts=("head",), bill="hook"),
    "Cape vultures": B(VULTURE, "Cape vulture", "Gyps coprotheres", "Cape vulture", col("#c8b89a", "#efe8dc", "#2a2420"), size=1.08,
                       dark_parts=("primaries",)),
    "lammergeiers": B(VULTURE, "Bearded vulture", "Gypaetus barbatus", "Bearded vulture", col("#3a3632", "#d88a4a", "#141210", "#e04a2a"),
                      size=1.1, bare=False, ruff=0.0, tail=6, pale_parts=("head", "belly", "neck"), dark_parts=("mask",)),
    "wedge-tailed eagles": B(RAPTOR, "Wedge-tailed eagle", "Aquila audax", "Wedge-tailed eagle", col("#2a2420", "#a87a50", "#141210"), size=1.08,
                             tail=6),
    "California quail": B(GROUNDBIRD, "California quail", "Callipepla californica", "California quail", col("#6a6e72", "#e6dccb", "#1e1c1a"),
                          crest=1.8, dark_parts=("crest", "mask"), pale_parts=("belly",), marks=("spots",)),

    # ---- flocks, vees, macaws --------------------------------------------------------------------------
    "starling murmurations": B(PASSERINE, "Common starling", "Sturnus vulgaris", "Common starling", col("#2a2a30", "#e8e2d4", "#121216"),
                               bill="long", bill_len=1.6, bill_role="eye", marks=("spots",), gait="fly"),
    "rosy starlings": B(PASSERINE, "Rosy starling", "Pastor roseus", "Rosy starling", col("#e8a8a0", "#f2d2cc", "#1e1a20"), crest=0.8,
                        dark_parts=("head", "wing", "tail"), bill_role="eye"),
    "common grackles": B(PASSERINE, "Common grackle", "Quiscalus quiscula", "Common grackle", col("#2a2632", "#6a5a8a", "#121016", "#e0d070"),
                         size=1.1, tail=4.4, bill="long", bill_len=1.8),
    "red-winged blackbirds": B(PASSERINE, "Red-winged blackbird", "Agelaius phoeniceus", "Red-winged blackbird", col("#1c1a1c", "#e04a2a", "#0e0c0e"),
                               bill="long", bill_len=1.6, pale_parts=("wing_patch",)),
    "crossbills": B(PASSERINE, "Red crossbill", "Loxia curvirostra", "Red crossbill", col("#b8483a", "#e08a6a", "#3a2a28"), bill="parrot",
                    bill_len=1.2, dark_parts=("wing", "tail")),
    "nutcrackers": B(PASSERINE, "Spotted nutcracker", "Nucifraga caryocatactes", "Spotted nutcracker", col("#5a4436", "#efe8dc", "#1e1814"),
                     size=1.15, bill="long", bill_len=2.0, marks=("spots",), dark_parts=("cap", "wing")),
    "bee-eaters": B(PASSERINE, "European bee-eater", "Merops apiaster", "European bee-eater", col("#3a9aa0", "#f0d040", "#1e1a18", "#e04a2a"),
                    bill="down", bill_len=2.4, tail=4.4, pale_parts=("throat",), dark_parts=("mask",)),
    "tui": B(PASSERINE, "Tūī", "Prosthemadera novaeseelandiae", "Tūī", col("#2a3a34", "#efebe4", "#121816"), size=1.15, bill="down",
             bill_len=1.6, ruff=0.7, pale_parts=("ruff",)),
    "snow buntings": B(PASSERINE, "Snow bunting", "Plectrophenax nivalis", "Snow bunting", col("#efebe4", "#f8f6f2", "#2a2624"),
                       dark_parts=("wing", "primaries")),
    "larks": B(PASSERINE, "Crested lark", "Galerida cristata", "Crested lark", col("#a08a6a", "#e6dac6", "#3a2e24"), crest=1.2, marks=("spots",),
               pale_parts=("belly",)),
    "weaverbirds": B(PASSERINE, "Village weaver", "Ploceus cucullatus", "Village weaver", col("#e8c030", "#f4e070", "#1e1a16", "#e04a2a"),
                     bill_len=1.4, dark_parts=("head", "wing_patch")),
    "Cape canaries": B(PASSERINE, "Cape canary", "Serinus canicollis", "Cape canary", col("#b8b040", "#f0e070", "#4a4a40"), pale_parts=("belly",)),
    "austral thrushes": B(PASSERINE, "Austral thrush", "Turdus falcklandii", "Austral thrush", col("#5a4a3a", "#c8a87a", "#1e1814", "#e0a020"),
                          size=1.1, bill="long", bill_role="eye", pale_parts=("belly",)),
    "eared doves": B(PASSERINE, "Eared dove", "Zenaida auriculata", "Eared dove", col("#8a7a6a", "#c8a898", "#2a2420"), size=1.15, bill="long",
                     bill_len=1.0, gait="walk", marks=("spots",)),
    "green pigeons": B(PASSERINE, "Green pigeon", "Treron", "Treron", col("#6a8a3a", "#c8d070", "#3a3a40", "#e04a2a"), size=1.15, bill_len=1.0),
    "fruit doves": B(PASSERINE, "Many-colored fruit dove", "Ptilinopus perousii", "Many-colored fruit dove", col("#7a9a4a", "#f0e090", "#a02a4a"),
                     size=1.1, bill_len=0.9, dark_parts=("cap",)),
    "parakeets": B(PARROT, "Green parakeet", "Psittacara holochlorus", "Green parakeet", col("#4a9a3a", "#a8d070", "#2a4a2a", "#e0b040"), size=0.85),
    "rose-ringed parakeets": B(PARROT, "Rose-ringed parakeet", "Psittacula krameri", "Rose-ringed parakeet", col("#5aa83a", "#b8e070", "#1e1a1a", "#e04a2a"),
                               size=0.85, tail=9, bill_role="eye"),
    "orange-fronted parakeets": B(PARROT, "Orange-fronted parakeet", "Eupsittula canicularis", "Orange-fronted parakeet",
                                  col("#5a9a3a", "#e8a040", "#2a4a2a"), size=0.82, pale_parts=("cap",)),
    "thick-billed parrots": B(PARROT, "Thick-billed parrot", "Rhynchopsitta pachyrhyncha", "Thick-billed parrot", col("#3a8a3a", "#d83a2a", "#1e2a1e"),
                              pale_parts=("cap",), dark_parts=("primaries",)),
    "austral parakeets": B(PARROT, "Austral parakeet", "Enicognathus ferrugineus", "Austral parakeet", col("#5a7a3a", "#a8484a", "#2a3a1e"),
                           size=0.85, bill_role="dark"),
    "blue-and-yellow macaws": B(PARROT, "Blue-and-yellow macaw", "Ara ararauna", "Blue-and-yellow macaw", col("#2a6ab0", "#f0c030", "#1e1e24"),
                                size=1.15, tail=10, pale_parts=("belly", "breast"), bill_role="dark"),
    "hyacinth macaws": B(PARROT, "Hyacinth macaw", "Anodorhynchus hyacinthinus", "Hyacinth macaw", col("#2a3a8a", "#f0d040", "#16163a"),
                         size=1.2, tail=10, bill_role="dark"),
    "scarlet macaws": B(PARROT, "Scarlet macaw", "Ara macao", "Scarlet macaw", col("#d02a20", "#f0d040", "#2a4ab0"), size=1.15, tail=10,
                        dark_parts=("primaries",), pale_parts=("wing_patch",), bill_role="pale"),
    "African grey parrots": B(PARROT, "Grey parrot", "Psittacus erithacus", "Grey parrot", col("#8a8a8a", "#d8d8d4", "#2a2a2a"), tail=3,
                              dark_parts=("primaries",)),
    "lorikeets": B(PARROT, "Rainbow lorikeet", "Trichoglossus moluccanus", "Rainbow lorikeet", col("#3a9a3a", "#e8a030", "#2a3a9a", "#e04a2a"),
                   size=0.85, dark_parts=("head",), pale_parts=("breast",), bill_role="eye"),
    "galahs": B(PARROT, "Galah", "Eolophus roseicapilla", "Galah", col("#8a8a8e", "#e88a9a", "#3a3a3e"), crest=1.0, pale_parts=("belly", "breast", "head")),
    "budgerigars": B(PARROT, "Budgerigar", "Melopsittacus undulatus", "Budgerigar", col("#7ab83a", "#f0e060", "#1e1e1a"), size=0.7, pale_parts=("head",),
                     marks=("bars",)),
    "sulphur-crested cockatoos": B(PARROT, "Sulphur-crested cockatoo", "Cacatua galerita", "Sulphur-crested cockatoo",
                                   col("#efebe4", "#f8f6f2", "#2a2624", "#e8d040"), size=1.05, crest=2.0, pale_parts=("crest",), bill_role="dark"),
    "rhinoceros hornbills": B(PARROT, "Rhinoceros hornbill", "Buceros rhinoceros", "Rhinoceros hornbill", col("#1e1c1a", "#efebe4", "#0e0c0a", "#e04a2a"),
                              size=1.2, bill="long", bill_len=3.2, casque=1.2, bill_role="pale", pale_parts=("tail", "belly")),
    "Canada geese": B(GOOSE, "Canada goose", "Branta canadensis", "Canada goose", col("#7a6a5a", "#efe8dc", "#1a1816"), size=1.05,
                      dark_parts=("neck", "head", "tail"), pale_parts=("belly",)),
    "greylag geese": B(GOOSE, "Greylag goose", "Anser anser", "Greylag goose", col("#8a8476", "#d8d2c8", "#3a3632"), size=1.05, bill_role="eye",
                       pale_parts=("belly",), eye_bill=True),
    "snow geese": B(GOOSE, "Snow goose", "Anser caerulescens", "Snow goose", col("#efebe4", "#f8f6f2", "#2a2624", "#e88a8a"), size=1.0,
                    dark_parts=("primaries",), bill_role="eye"),
    "bean geese": B(GOOSE, "Taiga bean goose", "Anser fabalis", "Taiga bean goose", col("#6a5a4a", "#c8bca8", "#2a2420", "#e8a030"), size=1.05,
                    dark_parts=("head", "neck"), bill_role="eye"),
    "red-breasted geese": B(GOOSE, "Red-breasted goose", "Branta ruficollis", "Red-breasted goose", col("#1e1c1c", "#efebe4", "#0e0c0c", "#b8481e"),
                            size=0.85, pale_parts=("belly",), dark_parts=("breast_dark",)),
    "upland geese": B(GOOSE, "Upland goose", "Chloephaga picta", "Upland goose", col("#8a8a86", "#efebe4", "#1e1c1a"), size=1.0,
                      pale_parts=("head", "neck", "belly"), marks=("bars",)),
    "swan geese": B(GOOSE, "Swan goose", "Anser cygnoides", "Swan goose", col("#8a7a66", "#e6dccb", "#3a2e24"), size=1.05, neck=4.6,
                    dark_parts=("cap",), pale_parts=("neck",)),
    "sandhill cranes": B(WADER, "Sandhill crane", "Antigone canadensis", "Sandhill crane", col("#8a8682", "#d8d4cc", "#2a2826", "#e04a2a"),
                         size=1.0, bill="long", bill_len=2.6, dark_parts=("cap",), bill_role="dark", leg_role="dark"),
    "Siberian cranes": B(WADER, "Siberian crane", "Leucogeranus leucogeranus", "Siberian crane", col("#efebe4", "#f8f6f2", "#1e1c1a", "#e04a2a"),
                         size=1.05, bill_len=2.8, dark_parts=("primaries", "mask"), bill_role="eye", leg_role="eye"),
    "demoiselle cranes": B(WADER, "Demoiselle crane", "Grus virgo", "Demoiselle crane", col("#9a9a9e", "#efebe4", "#1e1e20", "#e04a2a"),
                           size=0.9, bill_len=2.0, dark_parts=("neck", "head"), pale_parts=("ruff",), ruff=0.8),
    "black-necked cranes": B(WADER, "Black-necked crane", "Grus nigricollis", "Black-necked crane", col("#c8c4bc", "#efebe4", "#1a1818", "#e0c040"),
                             size=1.0, dark_parts=("neck", "head")),

    # ---- waders ---------------------------------------------------------------------------------------
    "grey herons": B(WADER, "Grey heron", "Ardea cinerea", "Grey heron", col("#8a8e94", "#efebe4", "#1e1e22", "#e8d040"), size=1.05,
                     bill_len=3.6, bill_role="eye", pale_parts=("neck", "head"), dark_parts=("primaries",)),
    "great egrets": B(WADER, "Great egret", "Ardea alba", "Great egret", col("#efebe4", "#f8f6f2", "#1e1c1a", "#e8c040"), size=1.05,
                      bill_len=3.4, bill_role="eye"),
    "egrets": B(WADER, "Little egret", "Egretta garzetta", "Little egret", col("#efebe4", "#f8f6f2", "#1e1c1a", "#e8c040"), size=0.85,
                bill_len=2.8, bill_role="dark", leg_role="dark"),
    "greater flamingos": B(WADER, "Greater flamingo", "Phoenicopterus roseus", "Greater flamingo", col("#ecb8b0", "#f6dad6", "#1e1a1a", "#e8c040"),
                           size=1.05, legs=11, neck=7.5, bill="bent", bill_len=2.6, bill_role="dark", leg_role="pale",
                           dark_parts=("primaries",)),
    "Andean and James's flamingos": B(WADER, "Andean flamingo", "Phoenicoparrus andinus", "Andean flamingo",
                                      col("#e8a8b8", "#f4d6dc", "#1e1a1a", "#e8c040"), size=1.0, legs=10.5, neck=7, bill="bent",
                                      bill_len=2.4, bill_role="dark", leg_role="eye", dark_parts=("primaries",)),
    "roseate spoonbills": B(WADER, "Roseate spoonbill", "Platalea ajaja", "Roseate spoonbill", col("#e88aa0", "#f4d4dc", "#d0303a", "#e04a2a"),
                            size=1.0, bill="spoon", bill_len=3.0, bill_role="pale", pale_parts=("neck", "head")),
    "African spoonbills": B(WADER, "African spoonbill", "Platalea alba", "African spoonbill", col("#efebe4", "#f8f6f2", "#c83a2a"), size=1.0,
                            bill="spoon", bill_len=3.0, bill_role="eye", leg_role="eye"),
    "scarlet ibises": B(WADER, "Scarlet ibis", "Eudocimus ruber", "Scarlet ibis", col("#e0402a", "#f08060", "#1e1a1a"), size=0.9, bill="down",
                        bill_len=3.2, dark_parts=("primaries",)),
    "jabirus": B(WADER, "Jabiru", "Jabiru mycteria", "Jabiru", col("#efebe4", "#f8f6f2", "#1a1818", "#d0302a"), size=1.15, bill="heavy",
                 bill_len=3.6, dark_parts=("head", "neck"), ruff=0.8, pale_parts=("ruff",)),
    "painted storks": B(WADER, "Painted stork", "Mycteria leucocephala", "Painted stork", col("#efebe4", "#e8a0a8", "#1e1c1a", "#e8c040"),
                        size=1.1, bill="down", bill_len=3.4, bill_role="eye", dark_parts=("primaries",), pale_parts=("tail",)),
    "wood storks": B(WADER, "Wood stork", "Mycteria americana", "Wood stork", col("#efebe4", "#f8f6f2", "#2a2624"), size=1.1, bill="down",
                     bill_len=3.2, dark_parts=("head", "primaries")),
    "shoebills": B(WADER, "Shoebill", "Balaeniceps rex", "Shoebill", col("#7a8288", "#b8bec4", "#2a2e32", "#e8d8a0"), size=1.15, bill="heavy",
                   bill_len=2.8, neck=4),
    "brolgas": B(WADER, "Brolga", "Antigone rubicunda", "Brolga", col("#9a9ea2", "#d8dcde", "#2a2a2c", "#e04a2a"), size=1.05, dark_parts=("cap",)),
    "pelicans": B(GOOSE, "Great white pelican", "Pelecanus onocrotalus", "Great white pelican", col("#efe6e0", "#f8f2ee", "#1e1c1a", "#e8c040"),
                  size=1.2, bill="long", bill_len=4.0, bill_role="eye", dark_parts=("primaries",), gait="fly"),
    "frigatebirds": B(RAPTOR, "Magnificent frigatebird", "Fregata magnificens", "Magnificent frigatebird", col("#1a1818", "#d02a2a", "#0e0c0c"),
                      size=1.0, bill="hook", bill_len=2.6, tilt=40, legs=1.4, tail=6, pale_parts=("throat",), bill_role="far"),

    # ---- hummers --------------------------------------------------------------------------------------
    "hummingbirds": B(HUMMER, "Rufous-tailed hummingbird", "Amazilia tzacatl", "Rufous-tailed hummingbird", col("#4a9a5a", "#c8784a", "#1e2a1e"),
                      pale_parts=("tail",), bill_role="dark"),
    "Anna's hummingbirds": B(HUMMER, "Anna's hummingbird", "Calypte anna", "Anna's hummingbird", col("#5a8a5a", "#e6e0d4", "#c02a6a"),
                             dark_parts=("head",), pale_parts=("belly",)),
    "green-backed firecrowns": B(HUMMER, "Green-backed firecrown", "Sephanoides sephaniodes", "Green-backed firecrown",
                                 col("#4a7a4a", "#d8d4c8", "#e0702a"), dark_parts=("cap",)),
    "sunbirds": B(HUMMER, "Olive sunbird", "Cyanomitra olivacea", "Olive sunbird", col("#7a8a3a", "#c8c86a", "#2a2e1e"), bill="down",
                  bill_len=2.0),
    "orange-breasted sunbirds": B(HUMMER, "Orange-breasted sunbird", "Anthobaphes violacea", "Orange-breasted sunbird",
                                  col("#3a8a5a", "#e88a2a", "#5a3a8a"), bill="down", bill_len=2.0, pale_parts=("belly", "breast")),
    "Cape sugarbirds": B(PASSERINE, "Cape sugarbird", "Promerops cafer", "Cape sugarbird", col("#7a6a5a", "#d8c8b0", "#2a2420", "#e8c040"),
                         size=1.1, bill="down", bill_len=2.2, tail=8, pale_parts=("belly",)),
    "spiderhunters": B(HUMMER, "Little spiderhunter", "Arachnothera longirostra", "Little spiderhunter", col("#6a8a3a", "#e8e080", "#2a2e1e"),
                       bill="down", bill_len=2.6, pale_parts=("belly",)),
    "honeyeaters": B(PASSERINE, "Wattled honeyeater", "Foulehaio carunculatus", "Wattled honeyeater", col("#6a6a3a", "#c8c070", "#2a2a1e", "#e8c040"),
                     bill="down", bill_len=1.6),
    "mangrove honeyeaters": B(PASSERINE, "Mangrove honeyeater", "Gavicalis fasciogularis", "Mangrove honeyeater", col("#6a6448", "#e8d070", "#2a2a1e"),
                              bill="down", bill_len=1.6, dark_parts=("mask",)),
    "kingfishers": B(PASSERINE, "Collared kingfisher", "Todiramphus chloris", "Collared kingfisher", col("#2a7ab0", "#f4f0e4", "#1e1e24"),
                     size=1.15, head=2.0, bill="long", bill_len=2.4, tail=2.6, pale_parts=("belly", "breast", "throat")),
    "hummingbird hawk-moths": S("Hummingbird hawk-moth", "Macroglossum stellatarum", "insect", "Hummingbird hawk-moth",
                                col("#7a6a5a", "#e09a4a", "#2a221c"), form="moth", marks=("stripes",)),
    "honey possums": Q(RODENT, "Honey possum", "Tarsipes rostratus", "Honey possum", col("#8a6e52", "#e0cdb0", "#2a1e16"), size=0.4, snout=3.0,
                       tail_len=9, marks=("belly", "dorsal")),
    "wattlebirds": B(PASSERINE, "Red wattlebird", "Anthochaera carunculata", "Red wattlebird", col("#5a4a3a", "#e6dccb", "#1e1814", "#e04a2a"),
                     size=1.2, bill="down", bill_len=1.8, tail=5, marks=("spots",)),

    # ---- frogs, lizards, crabs --------------------------------------------------------------------------
    "common frogs": S("Common frog", "Rana temporaria", "frog", "Common frog", col("#8a6a3e", "#d8c8a0", "#3a2a1a", "#c8a050"), marks=("mask", "spots", "belly")),
    "moor frogs": S("Moor frog", "Rana arvalis", "frog", "Moor frog", col("#8a7050", "#e0d4b8", "#3a2e20"), marks=("mask", "belly", "stripe")),
    "marsh frogs": S("Marsh frog", "Pelophylax ridibundus", "frog", "Marsh frog", col("#6a8a4a", "#d8d4b0", "#2a3a1e", "#c8a050"), marks=("spots", "belly")),
    "wood frogs": S("Wood frog", "Lithobates sylvaticus", "frog", "Wood frog", col("#9a6a3e", "#e0d0b4", "#2a1a10"), marks=("mask", "belly")),
    "spring peepers": S("Spring peeper", "Pseudacris crucifer", "frog", "Spring peeper", col("#a8885a", "#e8dcc4", "#4a3a26"), size=0.8,
                        marks=("belly",)),
    "pig frogs": S("Pig frog", "Lithobates grylio", "frog", "Pig frog", col("#4a5a30", "#d8d0a8", "#1e2414"), marks=("spots", "belly")),
    "Hochstetter's frogs": S("Hochstetter's frog", "Leiopelma hochstetteri", "frog", "Hochstetter's frog", col("#6a5a3a", "#a89a78", "#2a2418"),
                             size=0.85, marks=("spots",)),
    "Darwin's frogs": S("Darwin's frog", "Rhinoderma darwinii", "frog", "Darwin's frog", col("#5a7a3a", "#c8b880", "#1e1a16"), size=0.75,
                        marks=("belly",)),
    "paradoxical frogs": S("Paradoxical frog", "Pseudis paradoxa", "frog", "Paradoxical frog", col("#5a6e3a", "#c8c49a", "#2a2e1a"), marks=("stripe", "spots")),
    "poison dart frogs": S("Strawberry poison-dart frog", "Oophaga pumilio", "frog", "Strawberry poison-dart frog",
                           col("#d02a20", "#3a5ab0", "#141218"), size=0.8, marks=("spots",)),
    "reed frogs": S("Painted reed frog", "Hyperolius marmoratus", "frog", "Painted reed frog", col("#2a2420", "#f0e070", "#e04a2a"), size=0.8,
                    marks=("stripe",)),
    "painted reed frogs": S("Painted reed frog", "Hyperolius marmoratus", "frog", "Painted reed frog", col("#2a2420", "#f0e070", "#e04a2a"),
                            size=0.8, marks=("stripe",)),
    "Wallace's flying frogs": S("Wallace's flying frog", "Rhacophorus nigropalmatus", "frog", "Wallace's flying frog",
                                col("#3a9a3a", "#f0e070", "#1e2a1e"), marks=("belly",)),
    "green tree frogs": S("Australian green tree frog", "Ranoidea caerulea", "frog", "Australian green tree frog",
                          col("#5aa03a", "#efebe0", "#2a4a1e"), marks=("belly",)),
    "ocellated lizards": S("Ocellated lizard", "Timon lepidus", "lizard", "Ocellated lizard", col("#5a8a3a", "#3a7ab0", "#1e2a16", "#c8a050"),
                           size=1.1, marks=("ocelli", "belly"), **LIZARD),
    "fence lizards": S("Western fence lizard", "Sceloporus occidentalis", "lizard", "Western fence lizard", col("#6a5a4a", "#3a6ab0", "#1e1a16"),
                       marks=("bands", "belly"), **LIZARD),
    "girdled lizards": S("Cape girdled lizard", "Cordylus cordylus", "lizard", "Cape girdled lizard", col("#7a5a3a", "#c8a87a", "#2a1e16"),
                         spines=0.6, marks=("tailbands",), **LIZARD),
    "bobtail skinks": S("Shingleback skink", "Tiliqua rugosa", "lizard", "Shingleback skink", col("#5a3a2a", "#d8c8a8", "#1e1612"),
                        size=1.05, marks=("spots",), **mix(LIZARD, dict(tail=4.0, deep=2.0, head=1.9))),
    "Liolaemus lizards": S("Liolaemus lizard", "Liolaemus", "lizard", "Liolaemus", col("#7a6a4a", "#d8c8a0", "#2a2418"), marks=("stripes",), **LIZARD),
    "spiny-tailed lizards": S("Spiny-tailed lizard", "Uromastyx", "lizard", "Uromastyx", col("#c89a4a", "#e8d8a8", "#3a3024"), size=1.05,
                              marks=("tailbands", "spots"), **mix(LIZARD, dict(tail=7.0, deep=2.0, head=1.8))),
    "desert horned lizards": S("Desert horned lizard", "Phrynosoma platyrhinos", "lizard", "Desert horned lizard",
                               col("#b8966a", "#e8dcc4", "#4a3a2a"), spines=0.7, marks=("spots",), **mix(LIZARD, dict(tail=4.5, deep=1.9, body=5))),
    "thorny devils": S("Thorny devil", "Moloch horridus", "lizard", "Thorny devil", col("#b8743a", "#e8c88a", "#4a2a1a"), spines=1.0,
                       marks=("spots",), **mix(LIZARD, dict(tail=5, deep=1.9, body=5))),
    "lava lizards": S("Peruvian lava lizard", "Microlophus peruvianus", "lizard", "Microlophus peruvianus", col("#6a6050", "#c8b898", "#2a2620"),
                      marks=("spots", "throat"), **LIZARD),
    "spiny-tailed iguanas": S("Black spiny-tailed iguana", "Ctenosaura similis", "lizard", "Black spiny-tailed iguana",
                              col("#7a7a6a", "#c8c8b0", "#1e1e1a"), size=1.15, spines=0.8, marks=("tailbands",), **LIZARD),
    "garden lizards": S("Oriental garden lizard", "Calotes versicolor", "lizard", "Oriental garden lizard", col("#9a8a5a", "#e8d070", "#3a2e1e"),
                        spines=0.5, marks=("bands",), **LIZARD),
    "chameleons": S("Flap-necked chameleon", "Chamaeleo dilepis", "lizard", "Flap-necked chameleon", col("#6a9a3a", "#e0e070", "#2a3a1e"),
                    frill=1.2, marks=("stripes",), **LIZARD),
    "frilled lizards": S("Frilled-neck lizard", "Chlamydosaurus kingii", "lizard", "Frilled-neck lizard", col("#8a6a4a", "#d89a4a", "#2a2018"),
                         frill=2.2, **LIZARD),
    "geckos": S("Pacific gecko", "Gehyra oceanica", "lizard", "Gehyra oceanica", col("#a89a7a", "#e8e0c8", "#4a4030"), size=0.85,
                marks=("spots",), **LIZARD),
    "Namib web-footed geckos": S("Web-footed gecko", "Pachydactylus rangei", "lizard", "Pachydactylus rangei", col("#d8b89a", "#f0e6d8", "#5a4434"),
                                 size=0.85, **LIZARD),
    "yacare caimans": S("Yacare caiman", "Caiman yacare", "lizard", "Yacare caiman", col("#4a4a3a", "#c8c0a0", "#1e1e16", "#c8a050"), **CROC),
    "American crocodiles": S("American crocodile", "Crocodylus acutus", "lizard", "American crocodile", col("#6a6a4a", "#d8d0a8", "#2a2a1e", "#c8a050"),
                             size=1.1, **CROC),
    "estuarine crocodiles": S("Saltwater crocodile", "Crocodylus porosus", "lizard", "Saltwater crocodile", col("#5a5a3a", "#d8d0a8", "#1e1e14", "#c8a050"),
                              size=1.12, **CROC),
    "mudskippers": S("Giant mudskipper", "Periophthalmodon schlosseri", "lizard", "Giant mudskipper", col("#7a7060", "#d8d0c0", "#2a2620"),
                     size=0.8, marks=("spots",), **mix(LIZARD, dict(tail=4.0, legs=1.2, deep=1.6, head=1.8))),
    "fiddler crabs": S("Fiddler crab", "Uca", "crab", "Fiddler crab", col("#5a5a6a", "#e8e0d0", "#2a2a30"), claw=1.6, marks=("pale_claw",)),
    "mangrove crabs": S("Mangrove tree crab", "Aratus pisonii", "crab", "Aratus pisonii", col("#6a5a3a", "#c8a87a", "#2a2418"), claw=0.9),
    "mud crabs": S("Mud crab", "Scylla serrata", "crab", "Scylla serrata", col("#4a5a3a", "#b8a878", "#1e2418"), claw=1.1),

    # ---- snakes ----------------------------------------------------------------------------------------
    "adders": S("Common European adder", "Vipera berus", "snake", "Vipera berus", col("#8a8476", "#d8d0c0", "#1e1c1a", "#d8402a"),
                thick=1.15, marks=("zigzag",)),
    "garter snakes": S("Common garter snake", "Thamnophis sirtalis", "snake", "Common garter snake", col("#2e3a2e", "#e0d070", "#141a14"),
                       marks=("stripes",)),
    "Aesculapian snakes": S("Aesculapian snake", "Zamenis longissimus", "snake", "Aesculapian snake", col("#6a5a3a", "#e0d4a0", "#2a2418"),
                            length=34, thick=0.95, marks=("belly",)),
    "rubber boas": S("Northern rubber boa", "Charina bottae", "snake", "Northern rubber boa", col("#8a6a4a", "#d8b878", "#2a2018"),
                     thick=1.3, length=24, marks=("belly",)),
    "sidewinders": S("Sidewinder", "Crotalus cerastes", "snake", "Crotalus cerastes", col("#c8aa7a", "#ece0c8", "#5a4632"), thick=1.1,
                     length=24, marks=("blotches",)),
    "horned vipers": S("Saharan horned viper", "Cerastes cerastes", "snake", "Cerastes cerastes", col("#d0b080", "#efe4cc", "#6a5038"),
                       thick=1.2, length=24, marks=("blotches",)),
    "saw-scaled vipers": S("Indian saw-scaled viper", "Echis carinatus", "snake", "Echis carinatus", col("#a8865a", "#e8dcc0", "#3a2a1a"),
                           thick=1.0, length=22, marks=("zigzag",)),
    "Peruvian racers": S("Peruvian racer", "Lygophis", "snake", "Lygophis", col("#6a5a46", "#d8c8a0", "#2a2418"), marks=("stripes",)),
    "king cobras": S("King cobra", "Ophiophagus hannah", "snake", "King cobra", col("#4a4a32", "#e0d8a0", "#1e1e14"), length=36, thick=1.2,
                     hood=2.0, marks=("bands",)),
    "Indian cobras": S("Indian cobra", "Naja naja", "snake", "Indian cobra", col("#3a3028", "#d8c8a0", "#141210"), length=30, thick=1.15,
                       hood=2.4, marks=("belly",)),
    "coral snakes": S("Coral snake", "Micrurus", "snake", "Coral snake", col("#d03a2a", "#f0e070", "#141210"), thick=0.9, length=26,
                      marks=("bands",)),
    "boa constrictors": S("Boa constrictor", "Boa constrictor", "snake", "Boa constrictor", col("#a08a6a", "#d8c8a8", "#5a3a2a"),
                          thick=1.5, length=34, marks=("blotches",)),
    "Pacific boas": S("Pacific ground boa", "Candoia carinata", "snake", "Candoia carinata", col("#8a6a4a", "#d8c8a8", "#3a2a1e"),
                      thick=1.2, marks=("blotches",)),
    "Gaboon vipers": S("Gaboon viper", "Bitis gabonica", "snake", "Gaboon viper", col("#8a6a4a", "#e0d0b0", "#2a1e16"), thick=1.7,
                       length=24, head=1.7, marks=("blotches",)),
    "mangrove pit vipers": S("Mangrove pit viper", "Trimeresurus purpureomaculatus", "snake", "Trimeresurus purpureomaculatus",
                             col("#5a4a5a", "#c8c0b0", "#2a222a"), thick=1.1, marks=("blotches",)),
    "yellow anacondas": S("Yellow anaconda", "Eunectes notaeus", "snake", "Yellow anaconda", col("#b8a040", "#e8d880", "#1e1a14"), thick=1.8,
                          length=36, marks=("blotches",)),
    "green pythons": S("Green tree python", "Morelia viridis", "snake", "Green tree python", col("#3a9a3a", "#e8e070", "#1e3a1e"), thick=1.3,
                       marks=("spots",)),
    "garter snake": S("Common garter snake", "Thamnophis sirtalis", "snake", "Common garter snake", col("#2e3a2e", "#e0d070", "#141a14"),
                      marks=("stripes",)),

    # ---- insects ---------------------------------------------------------------------------------------
    "peacock butterflies": S("Peacock butterfly", "Aglais io", "insect", "Aglais io", col("#a82a20", "#e8d8a0", "#1e1a2a"), form="butterfly",
                             marks=("eyespot",)),
    "tiger swallowtails": S("Eastern tiger swallowtail", "Papilio glaucus", "insect", "Papilio glaucus", col("#e8c030", "#f4e080", "#1e1a16"),
                            form="butterfly", marks=("tigerstripes", "border")),
    "red admirals": S("Red admiral", "Vanessa atalanta", "insect", "Vanessa atalanta", col("#1e1a1a", "#e05a2a", "#0e0c0c"), form="butterfly",
                      marks=("band",)),
    "monarch butterflies in their winter clusters": S("Monarch butterfly", "Danaus plexippus", "insect", "Monarch butterfly",
                                                      col("#e0782a", "#f0e8d8", "#1e1a16"), form="butterfly", marks=("veins", "border")),
    "blue morphos": S("Blue morpho", "Morpho menelaus", "insect", "Morpho menelaus", col("#2a6ad8", "#7ab0f0", "#141820"), form="butterfly",
                      marks=("border",)),
    "Rajah Brooke's birdwings": S("Rajah Brooke's birdwing", "Trogonoptera brookiana", "insect", "Trogonoptera brookiana",
                                  col("#1a1e1c", "#3ad08a", "#0e100e"), form="butterfly", marks=("band",)),
    "African giant swallowtails": S("African giant swallowtail", "Papilio antimachus", "insect", "Papilio antimachus",
                                    col("#d0782a", "#f0c070", "#1e1612"), form="butterfly", marks=("border", "veins")),
    "migrating sulphurs": S("Cloudless sulphur", "Phoebis sennae", "insect", "Phoebis sennae", col("#f0d040", "#f8f0a0", "#7a6a2a"), form="butterfly"),
    "common Mormons": S("Common Mormon", "Papilio polytes", "insect", "Papilio polytes", col("#1e1c1c", "#efebe0", "#0e0c0c"), form="butterfly",
                        marks=("band",)),
    "eggfly butterflies": S("Great eggfly", "Hypolimnas bolina", "insect", "Hypolimnas bolina", col("#1e1a2a", "#e8e0f0", "#0e0c14"),
                            form="butterfly", marks=("eyespot",)),
    "comet moths": S("Comet moth", "Argema mittrei", "insect", "Comet moth", col("#e8c040", "#f4e080", "#a0402a"), form="butterfly", marks=("eyespot",)),
    "glow-worms": S("Common glow-worm", "Lampyris noctiluca", "insect", "Lampyris noctiluca", col("#5a4a3a", "#c8b898", "#1e1814", "#e8f070"),
                    form="beetle", glow=True),
    "fireflies": S("Firefly", "Photinus pyralis", "insect", "Photinus pyralis", col("#3a3632", "#e0a040", "#141210", "#e8f070"), form="beetle",
                   glow=True),
    "synchronous fireflies": S("Synchronous firefly", "Pteroptyx", "insect", "Pteroptyx", col("#6a5a3a", "#e0c070", "#1e1a14", "#e8f070"),
                               form="beetle", glow=True),
    "wood ants": S("Red wood ant", "Formica rufa", "insect", "Formica rufa", col("#a8482a", "#c8784a", "#1e1612"), form="ant"),
    "ants": S("Ant", "Formicidae", "insect", "Ant", col("#4a2e22", "#8a5a3a", "#141010"), form="ant"),
    "harvester ants": S("Red harvester ant", "Pogonomyrmex barbatus", "insect", "Pogonomyrmex barbatus", col("#a03a20", "#d8784a", "#1e1210"), form="ant"),
    "leafcutter ants": S("Leafcutter ant", "Atta", "insect", "Leafcutter ant", col("#9a4a2a", "#c87a4a", "#2a1610"), form="ant"),
    "army ants": S("Army ant", "Eciton burchellii", "insect", "Eciton burchellii", col("#6a3a20", "#a86a3a", "#1e1410"), form="ant"),
    "driver ants": S("Driver ant", "Dorylus", "insect", "Dorylus", col("#8a3a1e", "#c86a3a", "#1e120c"), form="ant"),
    "giant forest ants": S("Giant forest ant", "Dinomyrmex gigas", "insect", "Dinomyrmex gigas", col("#2a2220", "#8a3a2a", "#100c0a"), form="ant"),
    "Saharan silver ants": S("Saharan silver ant", "Cataglyphis bombycina", "insect", "Cataglyphis bombycina", col("#c8c4bc", "#efebe4", "#3a3632"),
                             form="ant"),
    "honeypot ants": S("Honeypot ant", "Camponotus inflatus", "insect", "Honeypot ant", col("#4a3020", "#e0a040", "#1e140c"), form="ant"),
    "darkling beetles": S("Darkling beetle", "Tenebrionidae", "insect", "Darkling beetle", col("#2a2624", "#6a625c", "#100e0c"), form="beetle"),
    "fog-basking beetles": S("Namib desert beetle", "Onymacris unguicularis", "insect", "Namib desert beetle", col("#1e1c1a", "#5a5650", "#0e0c0a"),
                             form="beetle"),
    "honey bees": S("Western honey bee", "Apis mellifera", "insect", "Western honey bee", col("#c8882a", "#e8d8b0", "#1e1612"), form="bee",
                    marks=("stripes",)),
    "Cape honey bees": S("Cape honey bee", "Apis mellifera capensis", "insect", "Apis mellifera capensis", col("#6a4a2a", "#e0d0b0", "#1e1612"),
                         form="bee", marks=("stripes",)),
    "native bees": S("Blue-banded bee", "Amegilla cingulata", "insect", "Amegilla cingulata", col("#3a3632", "#4a9ad0", "#141210"), form="bee",
                     marks=("stripes",)),
    "cicadas": S("Cicada", "Lyristes plebejus", "insect", "Lyristes plebejus", col("#5a4a3a", "#d8d0b8", "#1e1a14"), form="cicada"),
    "desert locusts": S("Desert locust", "Schistocerca gregaria", "insect", "Desert locust", col("#c8a040", "#e8d480", "#4a3a1e"), form="locust"),
    "locusts": S("Migratory locust", "Locusta migratoria", "insect", "Migratory locust", col("#8a8a4a", "#d8d090", "#3a3a1e"), form="locust"),
    "grasshoppers": S("Grasshopper", "Caelifera", "insect", "Grasshopper", col("#7a9a3a", "#d0d880", "#2a3a1e"), form="locust"),
    "red-billed quelea": B(PASSERINE, "Red-billed quelea", "Quelea quelea", "Red-billed quelea", col("#a08a6a", "#e8dcc4", "#1e1a16", "#e04a2a"),
                           size=0.9, bill_role="eye", dark_parts=("mask",), marks=("spots",)),
}


def get(key):
    sp = dict(SPECIES[key])
    sp["key"] = key
    return sp


# ---- where the grammar's realm-wide list is wider than the animal --------------------------
# DIRT's grammar gives species by biome and realm; some live in only part of a realm, and some
# are gone from part of it. A place takes a species only inside its range (boxes of lat0, lat1,
# lon0, lon1) and outside its gaps, from each species' range as its Wikipedia article gives it.
RANGE = {
    "Iberian ibex": [(35.5, 44.0, -10.0, 3.6)],                 # the Iberian Peninsula
    "Iberian lynx": [(35.5, 44.0, -10.0, 3.6)],
    "ocellated lizards": [(35.5, 45.5, -10.0, 8.6)],            # Iberia, southern France, north-west Italy
    "starling murmurations": [(34.0, 72.0, -11.0, 90.0)],       # Europe and western Asia (introduced elsewhere)
    "common frogs": [(40.0, 71.0, -11.0, 65.0)],                # Europe to the Urals
    "glow-worms": [(36.0, 64.0, -11.0, 100.0)],
    "wood ants": [(40.0, 66.0, -11.0, 100.0)],
    "white-tailed eagle": [(30.0, 72.0, -25.0, 180.0)],
    "pronghorn": [(22.0, 54.0, -125.0, -95.0)],                 # western North America, north of central Mexico
    "desert bighorn sheep": [(22.0, 42.0, -120.0, -100.0)],
    "grey squirrels": [(25.0, 50.0, -100.0, -60.0)],            # eastern North America
    "tiger swallowtails": [(25.0, 50.0, -100.0, -60.0)],
    "spring peepers": [(25.0, 52.0, -100.0, -60.0)],
    "common grackles": [(25.0, 56.0, -115.0, -60.0)],
}
GAPS = {
    "wolves": [(49.8, 61.0, -11.0, 2.0), (30.0, 46.0, 129.0, 146.0)],   # gone from the British Isles and Japan
    "adders": [(30.0, 46.0, 129.0, 146.0), (51.3, 55.5, -10.8, -5.4)],  # none in Japan or Ireland
    "wild boar": [(51.3, 55.5, -10.8, -5.4)],
}


def lives_at(key, lat, lon):
    inside = lambda bs: any(a <= lat <= b and c <= lon <= d for a, b, c, d in bs)
    if key in RANGE and not inside(RANGE[key]):
        return False
    return not (key in GAPS and inside(GAPS[key]))
